In [1]:
import pandas as pd
import numpy as np
import nltk

## import the Email Data

In [2]:
df=pd.read_csv("./Classification/NLP/email_data.xls")

In [3]:
df.shape

(5171, 4)

In [4]:
df.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\nth...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\n( see a...",0
2,3624,ham,"Subject: neon retreat\nho ho ho , we ' re arou...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\nthis deal is to ...,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5171 non-null   int64
 1   label       5171 non-null   object
 2   text        5171 non-null   object
 3   label_num   5171 non-null   int64
dtypes: int64(2), object(2)
memory usage: 161.7+ KB

In [6]:
df.label.value_counts()

label
ham     3672
spam    1499
Name: count, dtype: int64

## Data Cleaning And PreProcessing

In [7]:
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
stopwords=stopwords.words("english")  # English stopwords
from nltk.tokenize import word_tokenize
import re
from nltk.stem import WordNetLemmatizer
lemma=WordNetLemmatizer()

In [8]:
def clean(text) :
    text=re.sub("[^a-zA-Z]"," ",text)

    text=text.lower()

    text=word_tokenize(text,preserve_line=True)

    text=[x for x in text if x not in stopwords]

    test=[lemma.lemmatize(x) for x in text]

    return " ".join(text)

In [9]:
df["clean_text"] = df.text.apply(lambda x : clean(x ))

In [10]:
df.head()

,Unnamed: 0,label,text,label_num,clean_text
0,605,ham,Subject: enron methanol ; meter # : 988291\nth...,0,subject enron methanol meter follow note gave ...
1,2349,ham,"Subject: hpl nom for january 9 , 2001\n( see a...",0,subject hpl nom january see attached file hpln...
2,3624,ham,"Subject: neon retreat\nho ho ho , we ' re arou...",0,subject neon retreat ho ho ho around wonderful...
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1,subject photoshop windows office cheap main tr...
4,2030,ham,Subject: re : indian springs\nthis deal is to ...,0,subject indian springs deal book teco pvr reve...

##  Data Split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(df.clean_text,df.label_num ,test_size=0.2,random_state=1)

In [12]:
x_test.shape,x_train.shape

((1035,), (4136,))

## Data Transformation

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [14]:
x_train_trans=tfidf.fit_transform(x_train)
x_test_trans=tfidf.transform(x_test)

## Model Creation

In [15]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(x_train_trans,y_train)

LogisticRegression()

In [16]:
from sklearn.metrics import classification_report

In [21]:
predict=LR.predict(x_test_trans)
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       731
           1       0.97      0.99      0.98       304

    accuracy                           0.99      1035
   macro avg       0.99      0.99      0.99      1035
weighted avg       0.99      0.99      0.99      1035

## SVM

In [25]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train_trans,y_train)
predict=svc.predict(x_test_trans)
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       731
           1       0.98      1.00      0.99       304

    accuracy                           0.99      1035
   macro avg       0.99      0.99      0.99      1035
weighted avg       0.99      0.99      0.99      1035

## KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train_trans,y_train)
predict=knn.predict(x_test_trans)
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98       731
           1       0.98      0.90      0.94       304

    accuracy                           0.97      1035
   macro avg       0.97      0.95      0.96      1035
weighted avg       0.97      0.97      0.97      1035

## Decision Tree

In [24]:
from sklearn.tree import DecisionTreeClassifier
tree=KNeighborsClassifier()
tree.fit(x_train_trans,y_train)
predict=tree.predict(x_test_trans)
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98       731
           1       0.98      0.90      0.94       304

    accuracy                           0.97      1035
   macro avg       0.97      0.95      0.96      1035
weighted avg       0.97      0.97      0.97      1035

In [37]:
! git init

Reinitialized existing Git repository in C:/Users/pruth/Innomatics/Machine Learning/Supervised/.git/

In [36]:
!git remote add origin https://github.com/pruthvipatil26/ML-Case-Studies-.git
!git branch -M main
!git push -u origin main

error: remote origin already exists.
remote: Repository not found.
fatal: repository 'https://github.com/pruthvipatil26/Machine-Learning-Case-Studies-.git/' not found

In [34]:
!git push -u origin main

remote: Repository not found.
fatal: repository 'https://github.com/pruthvipatil26/Machine-Learning-Case-Studies-.git/' not found

In [35]:
!git push -u origin main

remote: Repository not found.
fatal: repository 'https://github.com/pruthvipatil26/Machine-Learning-Case-Studies-.git/' not found