# Working with Text Data - Preprocessing and Text to Numerical Vector

### Text Data

Text Analysis is a major application field for machine learning algorithms. Some of the major application areas of NLP are:
1. Spell Checker, Keyword Search, etc
2. Sentiment Analysis, Spam Classification
3. Machine Translation
4. Chatbots/Dialog Systems
5. Question Answering Systems
etc..

However the raw data, a sequence of symbols cannot be fed directly to the algorithms themselves as most of them expect numerical feature vectors with a fixed size rather than the raw text documents with variable length.

### Why NLP is hard?
1. Complexity of representation
2. Ambiguity in Natural Langugae


### Text Preprocessing

1. Tokenisation  
2. Removing special characters  
3. Convert sentence into lower case  
4. Removing stop words  
5. Stemming or Lemmatization


### Techniques to convert Text to Numerical Vectors

1. Bag of Words
2. TF IDF (Term Frequency - Inverse Document Frequency)
3. Word2Vec (by Google)
4. GloVe (Global Vectors by Stanford) - **Not Covered in this notebook**
5. Pretrained GloVe Embeddings
6. FastText (by Facebook) - **Not Covered in this notebook**
7. ELMo (Embeddings from Language Models) - **Not Covered in this notebook**
8. BERT (Bidirectional Encoder Representations from Transformer)

## Data Preparation

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
lst_text = ['it Was the best oF Times $', 
            'It was The worst of times.',
            'IT 9 was tHe age Of wisdom', 
            'it was thE age of foolishness']

df = pd.DataFrame({'text': lst_text})

df.head()

                            text
0     it Was the best oF Times $
1     It was The worst of times.
2     IT 9 was tHe age Of wisdom
3  it was thE age of foolishness

In [3]:
# !pip install nltk

In [4]:
import nltk
nltk.download('stopwords')
# Downloading wordnet before applying Lemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Client\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Client\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Client\AppData\Roaming\nltk_data...

True

- The code nltk.download('wordnet') downloads the WordNet corpus from the Natural Language Toolkit (NLTK) library. WordNet is a lexical database for the English language, which is widely used in natural language processing tasks such as word sense disambiguation, synonym detection, and semantic similarity calculation. By downloading the WordNet corpus, you gain access to a vast collection of words and their associated senses, relationships, and semantic information.

- The code nltk.download('omw-1.4') downloads the Open Multilingual WordNet (OMW) corpus from the Natural Language Toolkit (NLTK) library. Open Multilingual WordNet is an extension of WordNet that provides lexical information for multiple languages. By downloading the OMW corpus, you can access WordNet-like data for various languages, allowing you to perform multilingual natural language processing tasks such as cross-lingual word sense disambiguation, multilingual semantic similarity calculation, and multilingual ontology building.

In [5]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [6]:
## initialise the inbuilt Stemmer
stemmer = PorterStemmer()

In [7]:
## We can also use Lemmatizer instead of Stemmer
lemmatizer = WordNetLemmatizer()

## Text Preprocessing Steps

Text Preprocessing steps include some essential tasks to clean and remove the noise from the available data.

1. **Removing Special Characters and Punctuation**

2. **Converting to Lower Case** - We convert the whole text corpus to lower case to reduce the size of the vocabulary of our text data.

3. **Removing Stop Words** - Stopwords don't contribute to the meaning of a sentence. So, we can safely remove them without changing the meaning of the sentence. For eg: it, was, any, then, a, is, by, etc are the stopwords.

4. **Stemming or Lemmatization** - Stemming is the process of getting the root form of a word. For eg: warm, warmer, warming can be converted to warm.

In [8]:
raw_text = "This 1is Natural-LAnguage-Processing."
print(raw_text)

This 1is Natural-LAnguage-Processing.

In [9]:
# Removing special characters and digits
sentence = re.sub("[^a-zA-Z]", " ", raw_text)
print(sentence)

This  is Natural LAnguage Processing

In [10]:
# change sentence to lower case
sentence = sentence.lower()
print(sentence)

this  is natural language processing

In [11]:
# tokenize into words
tokens = sentence.split()
print(tokens)

['this', 'is', 'natural', 'language', 'processing']

In [12]:
# Removing stop words
clean_tokens = [t for t in tokens if t not in stopwords.words("english")]
print(clean_tokens)

['natural', 'language', 'processing']

In [13]:
# Stemming
clean_tokens_stem = [stemmer.stem(word) for word in clean_tokens]
print(clean_tokens_stem)

['natur', 'languag', 'process']

In [14]:
# Lemmatizing
clean_tokens_lem = [lemmatizer.lemmatize(word) for word in clean_tokens]
print(clean_tokens_lem)

['natural', 'language', 'processing']

In [15]:
## Lets put it all together

In [16]:
def preprocess(raw_text, flag):
    # Removing special characters and digits
    sentence = re.sub("[^a-zA-Z]", " ", raw_text)
    
    # change sentence to lower case
    sentence = sentence.lower()

    # tokenize into words
    tokens = sentence.split()
    
    # remove stop words                
    clean_tokens = [t for t in tokens if t not in stopwords.words("english")]
    
    # Stemming/Lemmatization
    if(flag == 'stem'):
        clean_tokens = [stemmer.stem(word) for word in clean_tokens]
    else:
        clean_tokens = [lemmatizer.lemmatize(word) for word in clean_tokens]
    
    return pd.Series([" ".join(clean_tokens), len(clean_tokens)])

In [17]:
temp_df = df['text'].apply(lambda x : preprocess(x, 'stem'))

temp_df.head()

             0  1
0    best time  2
1   worst time  2
2   age wisdom  2
3  age foolish  2

In [18]:
temp_df.columns = ['clean_text_stem', 'text_length_stem']

temp_df.head()

  clean_text_stem  text_length_stem
0       best time                 2
1      worst time                 2
2      age wisdom                 2
3     age foolish                 2

In [19]:
df = pd.concat([df, temp_df], axis=1)

df.head()

                            text clean_text_stem  text_length_stem
0     it Was the best oF Times $       best time                 2
1     It was The worst of times.      worst time                 2
2     IT 9 was tHe age Of wisdom      age wisdom                 2
3  it was thE age of foolishness     age foolish                 2

In [20]:
temp_df = df['text'].apply(lambda x: preprocess(x, 'lemma'))

temp_df.head()

                 0  1
0        best time  2
1       worst time  2
2       age wisdom  2
3  age foolishness  2

In [21]:
temp_df.columns = ['clean_text_lemma', 'text_length_lemma']

temp_df.head()

  clean_text_lemma  text_length_lemma
0        best time                  2
1       worst time                  2
2       age wisdom                  2
3  age foolishness                  2

In [22]:
df = pd.concat([df, temp_df], axis=1)

df.head()

                            text  ... text_length_lemma
0     it Was the best oF Times $  ...                 2
1     It was The worst of times.  ...                 2
2     IT 9 was tHe age Of wisdom  ...                 2
3  it was thE age of foolishness  ...                 2

[4 rows x 5 columns]

## Bag of Word Representation

We call vectorization the general process of turning a collection of text documents into numerical feature vectors. This specific strategy (tokenization, counting and normalization) is called the Bag of Words or "Bag of n-grams" representation. Documents are described by word occurrences while completely ignoring the relative position information of the words in the document.

We will use `CountVectorizer` to **convert text into a matrix of token count**.

`Bag of Words`: https://machinelearningmastery.com/gentle-introduction-bag-words-model/

`Code Example`: https://machinelearningmastery.com/prepare-text-data-machine-learning-scikit-learn/  

**We are going to perform below mentioned steps to understand the entire process:**  
a. Converting text to numerical vectors with the help of `CountVectorizer`  
b. Understand `fit` and `transform`  
c. Looking at `vocabulary_`  
d. Converting sparse matrix to dense matrix using `toarray()`  
e. Understanding `n_gram`  

### Advantages
1. It is simple to understand and implement like OneHotEncoding.
2. We have a fixed length encoding for any sequence of arbitrary length.
3. Documents with same words/vocabulary will have similar representation. So if two documents have a similar vocabulary, they’ll be closer to each other in the vector space and vice versa.

### Disadvantages
1. The size of vector increases with the size of the vocabulary. Thus, sparsity continues to be a problem. One way to control it is by limiting the vocabulary to n number of the most frequent words.
2. It does not capture the similarity between different words that mean the same thing. i.e. Semantic Meaning is not captured.
> a. "walk", "walked", and "walking". BoW vectors of all three tokens will be equally apart.  
> b. "search" and "explore" are synonyms. BoW won't capture the semantic similarity of these words.
3. This representation does not have any way to handle out of vocabulary (OOV) words (i.e., new words that were not seen in the corpus that was used to build the vectorizer).
4. As the name indicates, it is a “bag” of words. Word order information is lost in this representation. One way to control it is by using n-grams.
5. It suffers from **curse of high dimensionality.**

In [23]:
df.head()

                            text  ... text_length_lemma
0     it Was the best oF Times $  ...                 2
1     It was The worst of times.  ...                 2
2     IT 9 was tHe age Of wisdom  ...                 2
3  it was thE age of foolishness  ...                 2

[4 rows x 5 columns]

In [24]:
# Bag of Words

from sklearn.feature_extraction.text import CountVectorizer

# Initialize the "CountVectorizer" object, which is scikit-learn's
# bag of words tool.
vocab = CountVectorizer()

# fit_transform() does two functions: First, it fits the model
# and learns the vocabulary; second, it transforms our training data
# into feature vectors. The input to fit_transform should be a list of 
# strings.

dtm = vocab.fit_transform(df['clean_text_lemma'])

# fit_transform() could be done seperatly as mentioned below
# vocab.fit(df.clean_text_stem)
# dtm = vocab.transform(df.clean_text_stem)

In [25]:
# We can look at unique words by using 'vocabulary_'

vocab.vocabulary_

{'best': 1, 'time': 3, 'worst': 5, 'age': 0, 'wisdom': 4, 'foolishness': 2}

In [26]:
# Observe that the type of dtm is sparse

print(type(dtm))

<class 'scipy.sparse._csr.csr_matrix'>

In [27]:
# Lets now print the  shape of this dtm

print(dtm.shape)

# o/p -> (4, 6)
# i.e -> 4 documents and 6 unique words

(4, 6)

In [28]:
# Lets look at the dtm

print(dtm)

# Remember that dtm is a sparse matrix. i.e. zeros wont be stored
# Lets understand First line of output -> (0,1)    1
# Here (0, 1) means 0th document and 1st(index starting from 0) unique word. 
# (we have total 4 documents) & (we have total 6 unique words)
# (0, 1)    1 -> 1 here refers to the number of occurence of 1st word
# Now lets read it all in english.
# (0, 1)    1 -> 'times' occurs 1 time in 0th document. 
# Try to observe -> (3, 2)   1

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (4, 6)>
  Coords	Values
  (0, 1)	1
  (0, 3)	1
  (1, 3)	1
  (1, 5)	1
  (2, 0)	1
  (2, 4)	1
  (3, 0)	1
  (3, 2)	1

In [29]:
# Since the dtm is sparse, lets convert it into numpy array.

print(dtm.toarray())

[[0 1 0 1 0 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]
 [1 0 1 0 0 0]]

In [30]:
sorted(vocab.vocabulary_)

['age', 'best', 'foolishness', 'time', 'wisdom', 'worst']

In [31]:
pd.DataFrame(dtm.toarray(), columns=sorted(vocab.vocabulary_))

   age  best  foolishness  time  wisdom  worst
0    0     1            0     1       0      0
1    0     0            0     1       0      1
2    1     0            0     0       1      0
3    1     0            1     0       0      0

In [38]:
# 2-grams

vocab = CountVectorizer(ngram_range=(1,2))

dtm = vocab.fit_transform(df.clean_text_stem)

In [39]:
print(vocab.vocabulary_)

{'best': 3, 'time': 6, 'best time': 4, 'worst': 8, 'worst time': 9, 'age': 0, 'wisdom': 7, 'age wisdom': 2, 'foolish': 5, 'age foolish': 1}

In [40]:
# convert sparse matrix to numpy array
print(dtm.toarray())

[[0 0 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 1 1]
 [1 0 1 0 0 0 0 1 0 0]
 [1 1 0 0 0 1 0 0 0 0]]

In [41]:
pd.DataFrame(dtm.toarray(), columns=sorted(vocab.vocabulary_))

   age  age foolish  age wisdom  best  ...  time  wisdom  worst  worst time
0    0            0           0     1  ...     1       0      0           0
1    0            0           0     0  ...     1       0      1           1
2    1            0           1     0  ...     0       1      0           0
3    1            1           0     0  ...     0       0      0           0

[4 rows x 10 columns]

**Observations:**

- `vect.fit(lst_text)` **learns the vocabulary**
- `vect.transform(lst_text)` **uses the fitted vocabulary** to build a **document-term matrix**