In [2]:
import pandas as pd
import numpy as np
import sklearn 
import nltk
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
df=pd.read_csv("../email_data.xls")

In [57]:
df

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\nth...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\n( see a...",0
2,3624,ham,"Subject: neon retreat\nho ho ho , we ' re arou...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\nthis deal is to ...,0
...,...,...,...,...
5166,1518,ham,Subject: put the 10 on the ft\nthe transport v...,0
5167,404,ham,Subject: 3 / 4 / 2000 and following noms\nhpl ...,0
5168,2933,ham,Subject: calpine daily gas nomination\n>\n>\nj...,0
5169,1409,ham,Subject: industrial worksheets for august 2000...,0
5170,4807,spam,Subject: important online banking alert\ndear ...,1

In [58]:
import re
from nltk.stem import WordNetLemmatizer
lemm=WordNetLemmatizer()
def preprocessing(text):
    text=re.sub("[^a-zA-z]"," ",text)
    text=text.lower()
    text=text.split()
    text=[x for x in text if x not in stopwords.words("english")]
    text=[lemm.lemmatize(x) for x in text]
    return " ".join(text)

In [59]:
%%time
df["clean_text"]=df.text.apply(lambda x : preprocessing(x))

CPU times: total: 7min 16s
Wall time: 7min 32s

In [60]:
x

4282                           subject hl p recent number
2247    subject account bj hi sent email last week wan...
32      subject domestic employee participate enron co...
4254    subject first delivery cummings walker exxon v...
2860    subject aol instant messenger reconfirmation t...
                              ...
2763    subject [ ] driving dog cat call glrls \ \ ho ...
905     subject th change forwarded ami chokshi corp e...
3980    subject buy regalis also known superviagra cia...
235     subject x product please make sure clearly und...
5157    subject th change duke air liquide forwarded a...
Name: clean_text, Length: 4136, dtype: object

In [61]:
x,xt,y,yt=train_test_split(df.clean_text,df.label_num,test_size=0.2,random_state=1)

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
x_t=pd.DataFrame(tfidf.fit_transform(x).toarray(),columns=tfidf.get_feature_names_out())
xt_t=pd.DataFrame(tfidf.transform(xt).toarray(),columns=tfidf.get_feature_names_out())

In [81]:
xt_t

,aa,aaa,aabda,aabvmmq,aac,aachecar,aaer,aafco,aaiabe,aaigrcrb,...,zyl,zynsdirnh,zynve,zyqtaqlt,zyyqywp,zzezrjok,zzn,zzo,zzocb,zzsyt
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1031,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1032,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1034,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [91]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [102]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_t,y)
predict=knn.predict(xt_t)
predict

array([0, 0, 1, ..., 0, 0, 0])

In [103]:
print(classification_report(yt,predict))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98       731
           1       0.98      0.90      0.94       304

    accuracy                           0.97      1035
   macro avg       0.97      0.95      0.96      1035
weighted avg       0.97      0.97      0.97      1035

In [92]:
l=LogisticRegression()
l.fit(x_t,y)
predict=l.predict(xt_t)
print(classification_report(yt,predict))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       731
           1       0.97      1.00      0.98       304

    accuracy                           0.99      1035
   macro avg       0.98      0.99      0.99      1035
weighted avg       0.99      0.99      0.99      1035

In [106]:
df

,Unnamed: 0,label,text,label_num,clean_text
0,605,ham,Subject: enron methanol ; meter # : 988291\nth...,0,subject enron methanol meter follow note gave ...
1,2349,ham,"Subject: hpl nom for january 9 , 2001\n( see a...",0,subject hpl nom january see attached file hpln...
2,3624,ham,"Subject: neon retreat\nho ho ho , we ' re arou...",0,subject neon retreat ho ho ho around wonderful...
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1,subject photoshop window office cheap main tre...
4,2030,ham,Subject: re : indian springs\nthis deal is to ...,0,subject indian spring deal book teco pvr reven...
...,...,...,...,...,...
5166,1518,ham,Subject: put the 10 on the ft\nthe transport v...,0,subject put ft transport volume decreased cont...
5167,404,ham,Subject: 3 / 4 / 2000 and following noms\nhpl ...,0,subject following noms hpl take extra mmcf wee...
5168,2933,ham,Subject: calpine daily gas nomination\n>\n>\nj...,0,subject calpine daily gas nomination julie men...
5169,1409,ham,Subject: industrial worksheets for august 2000...,0,subject industrial worksheet august activity a...
5170,4807,spam,Subject: important online banking alert\ndear ...,1,subject important online banking alert dear va...