In [47]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split

In [48]:
df=pd.read_csv("./bengaluru_house_prices.csv")

In [49]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [50]:
df1=df.drop(columns=["area_type","availability","society","balcony"],axis=1)

In [51]:
df1

                       location       size total_sqft  bath   price
0      Electronic City Phase II      2 BHK       1056   2.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                      Kothanur      2 BHK       1200   2.0   51.00
...                         ...        ...        ...   ...     ...
13315                Whitefield  5 Bedroom       3453   4.0  231.00
13316             Richards Town      4 BHK       3600   5.0  400.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0  488.00
13319              Doddathoguru      1 BHK        550   1.0   17.00

[13320 rows x 5 columns]

In [52]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [53]:
df1.isna().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [54]:
df2=df1.dropna()

In [55]:
df2["size"]=df2["size"].apply(lambda x : x[0])

C:\Users\pruth\AppData\Local\Temp\ipykernel_20000\1399810983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["size"]=df2["size"].apply(lambda x : x[0])

In [56]:
df2["size"].isna().sum()

np.int64(0)

In [57]:
df2["size"]=df2["size"].astype(int)

C:\Users\pruth\AppData\Local\Temp\ipykernel_20000\1669050638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["size"]=df2["size"].astype(int)

In [36]:
if df2.size > df2.bath+1 :
    pass

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [37]:
df2

                       location  size total_sqft  bath   price
0      Electronic City Phase II     2       1056   2.0   39.07
1              Chikka Tirupathi     4       2600   5.0  120.00
2                   Uttarahalli     3       1440   2.0   62.00
3            Lingadheeranahalli     3       1521   3.0   95.00
4                      Kothanur     2       1200   2.0   51.00
...                         ...   ...        ...   ...     ...
13315                Whitefield     5       3453   4.0  231.00
13316             Richards Town     4       3600   5.0  400.00
13317     Raja Rajeshwari Nagar     2       1141   2.0   60.00
13318           Padmanabhanagar     4       4689   4.0  488.00
13319              Doddathoguru     1        550   1.0   17.00

[13246 rows x 5 columns]

In [69]:
df3=df2[df2["size"]>=df2.bath]

In [70]:
df3

                       location  size total_sqft  bath   price
0      Electronic City Phase II     2       1056   2.0   39.07
2                   Uttarahalli     3       1440   2.0   62.00
3            Lingadheeranahalli     3       1521   3.0   95.00
4                      Kothanur     2       1200   2.0   51.00
5                    Whitefield     2       1170   2.0   38.00
...                         ...   ...        ...   ...     ...
13314         Green Glen Layout     3       1715   3.0  112.00
13315                Whitefield     5       3453   4.0  231.00
13317     Raja Rajeshwari Nagar     2       1141   2.0   60.00
13318           Padmanabhanagar     4       4689   4.0  488.00
13319              Doddathoguru     1        550   1.0   17.00

[12320 rows x 5 columns]

In [79]:
df3.groupby("location")["location"].count()

location
 Anekal                 1
 Banaswadi              1
 Basavangudi            1
 Bhoganhalli            1
 Devarabeesana Halli    6
                       ..
t.c palya               1
tc.palya                4
vinayakanagar           1
white field,kadugodi    1
whitefiled              1
Name: location, Length: 1251, dtype: int64

In [84]:
df3[df3.location.value_counts()>10

C:\Users\pruth\AppData\Local\Temp\ipykernel_20000\1787763920.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3[df3.location.value_counts()>10]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [82]:
df3[df3.location.value_counts()>10]

C:\Users\pruth\AppData\Local\Temp\ipykernel_20000\1787763920.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3[df3.location.value_counts()>10]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [ ]:
df3.where()